/**
 * Automatically generated by expo-modules-test-core.
 *
 * This autogenerated file provides a mock for native Expo module,
 * and works out of the box with the expo jest preset.
 *  */

export async function create(
  domain: string,
  accountName: string,
  userIdBase64: string,
  challengeBase64: string,
  useSecurityKey: boolean
): Promise<any> {}

export async function sign(
  domain: string,
  challengeBase64: string,
  useSecurityKey: boolean
): Promise<any> {}
